name: FlameTech
version: '0.1.1'
main: cn.fandmc.flametech.Main
api-version: '1.21'
authors: [20018]
folia-supported: true
commands:
  flametech:
    description: 主命令
    usage: /flametech <二级命令>
    aliases: [ft]
