name: FlameTech CI/CD

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  actions: read
  packages: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version
        id: extract-version
        run: |
          PLUGIN_VERSION=$(awk -F': ' '/^version:/ {gsub(/[^0-9.]/, "", $2); print $2}' src/main/resources/plugin.yml)
          echo "version=$PLUGIN_VERSION" >> $GITHUB_OUTPUT
          echo "::notice::版本号: $PLUGIN_VERSION"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Grant gradlew Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Verify Build Artifact
        run: |
          if [ ! -f build/libs/FlameTech-*.jar ]; then
            echo "::error::未找到构建产物！"
            exit 1
          fi
          ls -lh build/libs/FlameTech-*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/libs/FlameTech-*.jar
          tag_name: v${{ steps.extract-version.outputs.version }}
          name: "FlameTech ${{ steps.extract-version.outputs.version }}"
          generate_release_notes: true

      - name: Get Timestamp
        id: get-time
        run: echo "current-time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
